blueprint:
  name: Outdoor light - temporary on (skip if already on)
  description: >
    Turns on an outdoor light for a duration when triggered (sunset->sunrise),
    but only if the light was OFF. If it was already ON, no timer/off is applied.
  domain: automation

  input:
    trigger_entity:
      name: Trigger entity (e.g., gate contact)
      selector:
        entity:

    light_entity:
      name: Light to control
      selector:
        entity:
          domain: light

    duration_minutes:
      name: Minutes to keep on
      default: 10
      selector:
        number:
          min: 1
          max: 120
          step: 1
          unit_of_measurement: minutes

trigger:
  - platform: state
    entity_id: !input trigger_entity
    to: "opening"

condition:
  - condition: sun
    after: sunset
    before: sunrise

action:
  - choose:
      # Only act if the light is currently OFF
      - conditions:
          - condition: state
            entity_id: !input light_entity
            state: "off"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light_entity

          - delay:
              minutes: !input duration_minutes

          - service: light.turn_off
            target:
              entity_id: !input light_entity

mode: restart