blueprint:
  name: Simple Ventilation Timer
  description: >
    Turns on a ventilation fan at a specific time for a specified duration.
    Useful for humidity control in bathrooms, laundry rooms, etc.
  domain: automation

  input:
    switch_entity:
      name: Ventilation switch to control
      selector:
        entity:
          domain: switch

    trigger_time:
      name: Time to turn on ventilation
      selector:
        time:

    duration_minutes:
      name: Duration to keep on (minutes)
      default: 30
      selector:
        number:
          min: 1
          max: 120
          step: 1
          unit_of_measurement: minutes

trigger:
  - platform: time
    at: !input trigger_time

action:
  - choose:
      # Only act if the switch is currently OFF
      - conditions:
          - condition: state
            entity_id: !input switch_entity
            state: "off"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input switch_entity

          - delay:
              minutes: !input duration_minutes

          - service: switch.turn_off
            target:
              entity_id: !input switch_entity

mode: single